version: '3.9'

services:
  cacheserver:
    image: htetlinmaung/cacheserver
    build: .
    ports:
      - "3030:3000"
    environment:
      - request_body_size=2gb
    restart: always
    volumes:
      - /home/hlm/app/cacheserver/settings.json:/app/settings.json
      - /home/hlm/app/cacheserver/domains.json:/app/domains.json
